# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Per La Gloria' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
    pod 'AFNetworking'
    pod 'M13ProgressSuite'
    pod 'SDWebImage'
    pod 'SideMenu'
    pod 'GoogleMaps'
  # Pods for Per La Glory

end
